version: "3.8"
services:
  order_service:
    build: ./order_service
    ports:
      - "8000:8000"
    depends_on:
      - inventory_service
    environment:
      - INVENTORY_SERVICE_URL=http://inventory_service:8001

  inventory_service:
    build: ./inventory_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///./inventory.db